# Generated by Django 2.2.8 on 2019-12-27 12:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('gestionPacientes', '0002_auto_20191125_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'centro_investigacion',
            },
        ),
        migrations.CreateModel(
            name='Centro_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'centro_medico',
            },
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Investigator_type', models.CharField(choices=[('Research', 'Investigador de busqueda'), ('Analisis', 'Investigador de analisis'), ('Otro', 'otro tipo de investigador')], max_length=10)),
                ('investigation_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Centro_investigacion')),
            ],
            options={
                'db_table': 'investigador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('board_number', models.CharField(max_length=250)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Centro_medico')),
            ],
            options={
                'db_table': 'medico',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('diabetes_type', models.CharField(choices=[('Tipo 1', 'Diabetes de tipo 1'), ('Tipo 2', 'Diabetes de tipo 2'), ('Otro', 'Diabetes de otro tipo')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Medico')),
            ],
            options={
                'db_table': 'paciente',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tratamiento',
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='casosformacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='casosseguimiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='destinodoc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dietas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentaciones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ejercicios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ficherosexportados',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gestionpedidosarticulos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gestionpedidosclientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gestionpedidospedidos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='glucemias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insulinas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mensajesusuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='momentos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='niveleje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pesos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pruebas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recomendaciones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipoeje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipoins',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipopru',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AddField(
            model_name='paciente',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Tratamiento'),
        ),
    ]
