# Generated by Django 2.2.8 on 2019-12-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0004_calorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ritmo_cardiaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('heart_rate', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'ritmo_cardiaco',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('steps', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'pasos',
                'unique_together': {('id_user', 'time')},
            },
        ),
    ]
