# Generated by Django 2.2.7 on 2019-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0004_centro_medico_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
