# Generated by Django 2.2.8 on 2020-01-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0006_siesta_suenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suenio_resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sleep_main_sleep', models.BooleanField()),
                ('sleep_efficiency', models.FloatField(max_length=250)),
                ('sleep_duration', models.FloatField(max_length=250)),
                ('sleep_minutes_asleep', models.FloatField(max_length=250)),
                ('sleep_minutes_light', models.FloatField(max_length=250)),
                ('sleep_minutes_deep', models.FloatField(max_length=250)),
                ('sleep_minutes_rem', models.FloatField(max_length=250)),
                ('sleep_minutes_awake', models.FloatField(max_length=250)),
                ('sleep_minutes_in_bed', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'suenio_resumen',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Siesta_resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('nap_main_sleep', models.BooleanField()),
                ('nap_efficiency', models.FloatField(max_length=250)),
                ('nap_duration', models.FloatField(max_length=250)),
                ('nap_minutes_asleep', models.FloatField(max_length=250)),
                ('nap_minutes_light', models.FloatField(max_length=250)),
                ('nap_minutes_deep', models.FloatField(max_length=250)),
                ('nap_minutes_rem', models.FloatField(max_length=250)),
                ('nap_minutes_awake', models.FloatField(max_length=250)),
                ('nap_minutes_in_bed', models.FloatField(max_length=250)),
                ('nap_minutes_restless', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'siesta_resumen',
                'unique_together': {('id_user', 'time')},
            },
        ),
    ]
