# Generated by Django 2.2.8 on 2020-01-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0007_siesta_resumen_suenio_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_glucose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sensor_glucose_mg_dL', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'sensor_glucose',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Sensor_calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sensor_calibration_mg_dL', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'sensor_calibration',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Bwz_carb_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bwz_carb_ratio_U_EX', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'bwz_carb_ratio',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Bwz_carb_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bwz_carb_input_EX', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'bwz_carb_input',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Bolus_volume_delivered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bolus_volume_delivered_U', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'bolus_volume_delivered',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Bolus_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bolus_type', models.CharField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'bolus_type',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Bg_reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bg_reading_mg_dL', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'bg_reading',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Basal_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('basal_rate_U_h', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'basal_rate',
                'unique_together': {('id_user', 'time')},
            },
        ),
    ]
