# Generated by Django 2.2.8 on 2020-01-04 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0008_basal_rate_bg_reading_bolus_type_bolus_volume_delivered_bwz_carb_input_bwz_carb_ratio_sensor_calibra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulina_rapida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('insulina_rapida_U', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'insulina_rapida',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Insulina_lenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('insulina_lenta_U', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'insulina_lenta',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Glucosa_sangre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('glucosa_sangre_mg_dL', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'glucosa_sangre',
                'unique_together': {('id_user', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Cetonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('cetonas_mmol_L', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'cetonas',
                'unique_together': {('id_user', 'time')},
            },
        ),
    ]
