# Generated by Django 2.2.8 on 2020-01-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0009_cetonas_glucosa_sangre_insulina_lenta_insulina_rapida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('peso', models.FloatField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'peso',
                'unique_together': {('id_user', 'time')},
            },
        ),
    ]
