# Generated by Django 2.2.8 on 2020-01-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0010_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito_roche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('hito_roche', models.CharField(max_length=250)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionPacientes.Paciente')),
            ],
            options={
                'db_table': 'hito_roche',
                'unique_together': {('id_user', 'time')},
            },
        ),
    ]
