# Generated by Django 2.2.8 on 2020-01-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0011_hito_roche'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='first_date',
            field=models.DateTimeField(blank=True, help_text='Primera fecha con datos del paciente', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='last_date',
            field=models.DateTimeField(blank=True, help_text='Ultima fecha con datos del paciente', null=True),
        ),
    ]
