# Generated by Django 2.2.7 on 2019-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasosFormacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alcohol', models.IntegerField(blank=True, null=True)),
                ('blobrecs', models.TextField(blank=True, db_column='blobRecs', null=True)),
                ('cetoacidosis', models.IntegerField(blank=True, db_column='Cetoacidosis', null=True)),
                ('cetonicos', models.IntegerField(blank=True, null=True)),
                ('conocimientos_infor', models.IntegerField(blank=True, null=True)),
                ('control_alimentacion', models.IntegerField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('frecuencia_deporte', models.IntegerField(blank=True, null=True)),
                ('glicosilada', models.IntegerField(blank=True, null=True)),
                ('glucemia_postdeporte', models.IntegerField(blank=True, null=True)),
                ('hiperglucemia', models.IntegerField(blank=True, null=True)),
                ('hipoglucemia', models.IntegerField(blank=True, null=True)),
                ('indice_glucemico', models.IntegerField(blank=True, null=True)),
                ('intensidad_deporte', models.IntegerField(blank=True, null=True)),
                ('moodle', models.IntegerField(blank=True, null=True)),
                ('perfiles', models.IntegerField(blank=True, null=True)),
                ('practica_deporte', models.IntegerField(blank=True, null=True)),
                ('sense', models.IntegerField(blank=True, null=True)),
                ('situaciones_tensas', models.IntegerField(blank=True, null=True)),
                ('tomas_extras', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casos_formacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasosSeguimiento',
            fields=[
                ('caseid', models.AutoField(db_column='caseID', primary_key=True, serialize=False)),
                ('blobrecs', models.TextField(blank=True, db_column='blobRecs', null=True)),
                ('cetonicos', models.IntegerField(blank=True, null=True)),
                ('ejercicio', models.IntegerField(blank=True, null=True)),
                ('fondoojos', models.IntegerField(blank=True, db_column='fondoOjos', null=True)),
                ('hba1c', models.IntegerField(blank=True, null=True)),
                ('imc', models.IntegerField(blank=True, null=True)),
                ('h1', models.IntegerField(blank=True, null=True)),
                ('h2', models.CharField(blank=True, max_length=45, null=True)),
                ('h3', models.CharField(blank=True, max_length=45, null=True)),
                ('h4', models.CharField(blank=True, max_length=45, null=True)),
                ('h5', models.CharField(blank=True, max_length=45, null=True)),
                ('h6', models.CharField(blank=True, max_length=45, null=True)),
                ('h7', models.CharField(blank=True, max_length=45, null=True)),
                ('h8', models.CharField(blank=True, max_length=45, null=True)),
                ('h9', models.CharField(blank=True, max_length=45, null=True)),
                ('h10', models.CharField(blank=True, max_length=45, null=True)),
                ('h11', models.CharField(blank=True, max_length=45, null=True)),
                ('h12', models.CharField(blank=True, max_length=45, null=True)),
                ('h13', models.CharField(blank=True, max_length=45, null=True)),
                ('h14', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'casos_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DestinoDoc',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=45)),
            ],
            options={
                'db_table': 'destino_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('moment', models.IntegerField(blank=True, db_column='MOMENT', null=True)),
                ('observations', models.CharField(blank=True, db_column='OBSERVATIONS', max_length=255, null=True)),
                ('raciones', models.FloatField(blank=True, db_column='RACIONES', null=True)),
            ],
            options={
                'db_table': 'dietas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentaciones',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('fichero', models.TextField(blank=True, db_column='FICHERO', null=True)),
                ('filename', models.CharField(blank=True, db_column='FILENAME', max_length=255, null=True)),
                ('filesize', models.BigIntegerField(blank=True, db_column='FILESIZE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('tipodestino', models.BigIntegerField(blank=True, db_column='TIPODESTINO', null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True)),
                ('filetype', models.CharField(blank=True, db_column='FILETYPE', max_length=64, null=True)),
            ],
            options={
                'db_table': 'documentaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('level', models.IntegerField(blank=True, db_column='LEVEL', null=True)),
                ('type', models.IntegerField(blank=True, db_column='TYPE', null=True)),
            ],
            options={
                'db_table': 'ejercicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficherosexportados',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
                ('filepath', models.CharField(blank=True, db_column='FILEPATH', max_length=255, null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
            ],
            options={
                'db_table': 'ficherosexportados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionpedidosArticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'gestionpedidos_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionpedidosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'gestionpedidos_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionpedidosPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('entregado', models.IntegerField()),
            ],
            options={
                'db_table': 'gestionpedidos_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glucemias',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('moment', models.IntegerField(blank=True, db_column='MOMENT', null=True)),
                ('observations', models.CharField(blank=True, db_column='OBSERVATIONS', max_length=255, null=True)),
                ('value', models.FloatField(blank=True, db_column='VALUE', null=True)),
            ],
            options={
                'db_table': 'glucemias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insulinas',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('moment', models.IntegerField(blank=True, db_column='MOMENT', null=True)),
                ('type', models.IntegerField(blank=True, db_column='TYPE', null=True)),
                ('value', models.FloatField(blank=True, db_column='VALUE', null=True)),
            ],
            options={
                'db_table': 'insulinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajesUsuario',
            fields=[
                ('mensajeid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('nuevo', models.IntegerField(blank=True, null=True)),
                ('recomendacionid', models.IntegerField(blank=True, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensajes_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('modelo', models.CharField(db_column='MODELO', max_length=512)),
                ('fecha', models.DateTimeField(db_column='FECHA')),
                ('idpaciente', models.IntegerField(db_column='IDPACIENTE')),
            ],
            options={
                'db_table': 'modelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Momentos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=45)),
                ('hourfrom', models.SmallIntegerField(blank=True, db_column='HOURFROM', null=True)),
                ('hourto', models.SmallIntegerField(blank=True, db_column='HOURTO', null=True)),
            ],
            options={
                'db_table': 'momentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelEje',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=45)),
            ],
            options={
                'db_table': 'nivel_eje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('peso', models.FloatField(blank=True, db_column='PESO', null=True)),
            ],
            options={
                'db_table': 'pesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('clave', models.BigAutoField(db_column='CLAVE', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('fichero', models.TextField(blank=True, db_column='FICHERO', null=True)),
                ('filename', models.CharField(blank=True, db_column='FILENAME', max_length=255, null=True)),
                ('filesize', models.BigIntegerField(blank=True, db_column='FILESIZE', null=True)),
                ('iduser', models.BigIntegerField(blank=True, db_column='IDUSER', null=True)),
                ('type', models.IntegerField(blank=True, db_column='TYPE', null=True)),
                ('filetype', models.CharField(blank=True, db_column='FILETYPE', max_length=64, null=True)),
            ],
            options={
                'db_table': 'pruebas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recomendaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEje',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=45)),
            ],
            options={
                'db_table': 'tipo_eje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIns',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=45)),
            ],
            options={
                'db_table': 'tipo_ins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPru',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=45)),
            ],
            options={
                'db_table': 'tipo_pru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=255, null=True)),
                ('altacurso', models.IntegerField(blank=True, db_column='ALTACURSO', null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('dni', models.CharField(blank=True, db_column='DNI', max_length=32, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=255, null=True, unique=True)),
                ('examen', models.BigIntegerField(blank=True, db_column='EXAMEN', null=True)),
                ('fechaevaluacion', models.DateTimeField(blank=True, db_column='FECHAEVALUACION', null=True)),
                ('firmacontrato', models.IntegerField(blank=True, db_column='FIRMACONTRATO', null=True)),
                ('height', models.FloatField(blank=True, db_column='HEIGHT', null=True)),
                ('iddoctor', models.BigIntegerField(blank=True, db_column='IDDOCTOR', null=True)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=255, null=True)),
                ('login', models.BigIntegerField(blank=True, db_column='LOGIN', null=True)),
                ('moodleid', models.IntegerField(blank=True, db_column='MOODLEID', null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=64, null=True)),
                ('nivel', models.IntegerField(blank=True, db_column='NIVEL', null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=32, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=32, null=True)),
                ('phone2', models.CharField(blank=True, db_column='PHONE2', max_length=32, null=True)),
                ('rolcurso', models.IntegerField(blank=True, db_column='ROLCURSO', null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=6, null=True)),
                ('surname1', models.CharField(blank=True, db_column='SURNAME1', max_length=64, null=True)),
                ('surname2', models.CharField(blank=True, db_column='SURNAME2', max_length=64, null=True)),
                ('fechaconsen', models.DateTimeField(blank=True, db_column='FECHACONSEN', null=True)),
                ('hipergluc', models.IntegerField(blank=True, db_column='HIPERGLUC', null=True)),
                ('hipogluc', models.IntegerField(blank=True, db_column='HIPOGLUC', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
